# Generated by Django 4.2.11 on 2024-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'yazı', 'verbose_name_plural': 'yazılar'},
        ),
        migrations.AddField(
            model_name='blog',
            name='broadcast',
            field=models.BooleanField(default=True, verbose_name='yayın mı?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ekleme tarihi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='guncelleme tarihi'),
        ),
    ]
