# Generated by Django 4.2.11 on 2024-04-26 17:08

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_blog_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mekanın adı')),
                ('location', djgeojson.fields.PointField(verbose_name='lokasyon')),
            ],
            options={
                'verbose_name': 'mekan',
                'verbose_name_plural': 'mekanlar',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='kategorinin adı'),
        ),
    ]
