# Generated by Django 4.2.11 on 2024-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_place_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='defaults/default.png', upload_to='blog/', verbose_name='resim'),
        ),
    ]
